default: &default
  tax_rates:
    standard: 0.10
    exempt: 0.00
    import: 0.05
  exempt_tax_product_types:
    - book
    - food
    - medical
  product_types:
    food:
      - chocolate bar
      - chocolates
    medical:
      - pills
    book:
      - book

development:
  <<: *default

production:
  <<: *default
